### ISSUE TITLE
关于事件模块的问题

### ISSUE THREAD

**Issue by SixGodZhang** [coding2233/UnityGameFramework#3]
```
private static Dictionary<int,Action<object, IEventArgs>>
public void AddListener<T>(Action<object, IEventArgs> handler) where T : IEventArgs
public void RemoveListener<T>(Action<object, IEventArgs> handler) where T : IEventArgs
public void Trigger(object sender, IEventArgs eventArgs)
```
我在看代码时想到以下问题,烦请指教，非常感谢:
1.把IEventArg作为事件ID，会产生大量具有相同数据类型的类,比如HttpReadTextSuccessEventArgs、HttpReadTextFaileEventArgs、DownloadSuccessEventArgs。这三个持有的成员类型是一样的，仅仅因为需要将其作为事件ID，我就要创建三个类型，这样是否不太好?
2.在进行事件触发时，会根据参数类型触发与之相关的所有事件，比如我A类中下载一个文本，我在B类中也下载一个文本，A或B中任意一个下载完毕都会去调用所有下载完成的事件。除非我在A类和B类中用不通的事件参数类型，这样一来，又增加了代码的冗余，，，

**Comment by SixGodZhang** [comment]
斗胆，写了这样一个Demo:
```
//-----------------------------------------------------------------------
// <filename>EventManager</fileName>
// <copyright>
//     Copyright (c) 2018 Zhang Hui. All rights reserved.
// </copyright>
// <describe> ## </describe>
// <email> whdhxyzh@gmail.com </email>
// <time> #2018/11/30 星期五 16:15:46# </time>
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

namespace GameFramework.Taurus
{
    /// <summary>
    /// 事件管理类
    /// </summary>
    public class EventManager : IGameModule
    {
        #region 字段&属性
        private static Dictionary<int,Action<object, IEventArgs>> _allActions = new Dictionary<int, Action<object, IEventArgs>>();
        #endregion

        #region 公开接口

        /// <summary>
        /// 获取事件ID
        /// 此事件ID属于应用程序级别，最高级别。可以通过<b>事件类型</b>调用
        /// 可以跨类被同时触发
        /// </summary>
        /// <param name="eventType"></param>
        /// <returns></returns>
        public static int GetEventID(EventType eventType)
        {
            return (int)eventType;
        }
        
        /// <summary>
        /// 获取事件ID
        /// 此事件ID属于类级别,可以通过<b>类型+事件类型</b>调用
        /// 同一类型上同种事件会被同时触发
        /// </summary>
        /// <param name="type">挂在事件的类型</param>
        /// <param name="eventType">事件类型(触发类型)</param>
        /// <param name="istoeventtype">在类型为null值，是否转成 通过事件类型触发</param>
        /// <returns></returns>
        public static int GetEventID(Type type, EventType eventType,bool istoeventtype = false)
        {
            if (type == null && istoeventtype)
                return GetEventID(eventType);
            else if (type == null)
                return -1;
            else
                return type.GetHashCode() * (int)eventType;
        }

        /// <summary>
        /// 获取事件ID
        /// 此事件ID数据实例级别,可以通过<b>实例+事件类型调用</b>
        /// </summary>
        /// <param name="instance">实例</param>
        /// <param name="eventType">事件类型(触发类型)</param>
        /// <param name="istoeventtype">在类型为null值，是否转成 通过事件类型触发</param>
        /// <returns></returns>
        public static int GetEventID(UnityEngine.Object instance, EventType eventType, bool istoeventtype = false)
        {
            if (instance == null && istoeventtype)
                return GetEventID(eventType);
            else if (instance == null)
                return -1;
            else
                return instance.GetInstanceID() * (int)eventType;
        }

        /// <summary>
        /// 添加监听事件
        /// </summary>
        /// <param name="eventType">事件类型</param>
        /// <param name="handler">事件</param>
        public void AddListener(int eventid, Action<object, IEventArgs> handler)
        {
            Action<object, IEventArgs> eventHandler =null;
            if (!_allActions.TryGetValue(eventid, out eventHandler))
                _allActions[eventid] = handler;
            else
                eventHandler += handler;
        }

        /// <summary>
        /// 移除监听事件
        /// </summary>
        /// <param name="instance">实例</param>
        /// <param name="eventType">事件类型</param>
        /// <param name="handler">事件</param>
        public void RemoveListener(int eventid, Action<object,IEventArgs> handler)
        {
            Action<object, IEventArgs> eventHandler = null;
            if (!_allActions.TryGetValue(eventid, out eventHandler))
                return;
            else
            {
                eventHandler -= handler;
                if (eventHandler == null)
                    _allActions.Remove(eventid);
            }
        }

        /// <summary>
        /// 触发事件
        /// </summary>
        /// <param name="eventid"></param>
        public void Trigger(UnityEngine.Object sender, int eventid,IEventArgs eventArgs = null)
        {
            HanleEvent(sender, eventid,eventArgs);
        }

        #endregion

        #region 内部函数
        private void HanleEvent(UnityEngine.Object sender, int eventid, IEventArgs eventArgs = null)
        {
            Action<object, IEventArgs> eventHandler = null;
            if (!_allActions.TryGetValue(eventid, out eventHandler))
            {
#if UNITY_EDITOR
                UnityEngine.Debug.LogError("找不到事件! \n " + System.Environment.StackTrace);
#endif
                return;
            }
            eventHandler(sender, eventArgs);
        }
        #endregion

        #region 重载函数
        /// <summary>
        /// 清空所有事件
        /// </summary>
        public void OnClose()
        {
            _allActions.Clear();
        }
        #endregion
    }

    //public void RegisterAndCallEvent(){
    //    EventManager eventManager = new EventManager();
    //    int eventid = -1;
    //            if ((eventid = EventManager.GetEventID(this, EventType.HttpDownLoadSuccess)) != -1)
    //                eventManager.AddListener(eventid,OnHttpDownLoad);

    //    eventManager.Trigger(null, eventid);
    //}

    //private void OnHttpDownLoad(object arg1, IEventArgs arg2)
    //{
    //    //....
    //}

}

```

**Comment by coding2233** [comment]
> ```
> private static Dictionary<int,Action<object, IEventArgs>>
> public void AddListener<T>(Action<object, IEventArgs> handler) where T : IEventArgs
> public void RemoveListener<T>(Action<object, IEventArgs> handler) where T : IEventArgs
> public void Trigger(object sender, IEventArgs eventArgs)
> ```
> 我在看代码时想到以下问题,烦请指教，非常感谢:
> 1.把IEventArg作为事件ID，会产生大量具有相同数据类型的类,比如HttpReadTextSuccessEventArgs、HttpReadTextFaileEventArgs、DownloadSuccessEventArgs。这三个持有的成员类型是一样的，仅仅因为需要将其作为事件ID，我就要创建三个类型，这样是否不太好?
> 2.在进行事件触发时，会根据参数类型触发与之相关的所有事件，比如我A类中下载一个文本，我在B类中也下载一个文本，A或B中任意一个下载完毕都会去调用所有下载完成的事件。除非我在A类和B类中用不通的事件参数类型，这样一来，又增加了代码的冗余，，，

@SixGodZhang  其实你担心的问题确实是存在的，一方面担心事件分太细会造成代码的冗余，一方面担心不分太细会多次调用无关的委托。 我的建议是，根据实际灵活处理，该分类就分类， 不用分类多调一两个委托是没关系的，不要为了这点性能纠结，开发得爽才更重要

**Comment by coding2233** [comment]
> 斗胆，写了这样一个Demo:
> 
> ```
> //-----------------------------------------------------------------------
> // <filename>EventManager</fileName>
> // <copyright>
> //     Copyright (c) 2018 Zhang Hui. All rights reserved.
> // </copyright>
> // <describe> ## </describe>
> // <email> whdhxyzh@gmail.com </email>
> // <time> #2018/11/30 星期五 16:15:46# </time>
> //-----------------------------------------------------------------------
> 
> using System;
> using System.Collections.Generic;
> using UnityEngine;
> 
> namespace GameFramework.Taurus
> {
>     /// <summary>
>     /// 事件管理类
>     /// </summary>
>     public class EventManager : IGameModule
>     {
>         #region 字段&属性
>         private static Dictionary<int,Action<object, IEventArgs>> _allActions = new Dictionary<int, Action<object, IEventArgs>>();
>         #endregion
> 
>         #region 公开接口
> 
>         /// <summary>
>         /// 获取事件ID
>         /// 此事件ID属于应用程序级别，最高级别。可以通过<b>事件类型</b>调用
>         /// 可以跨类被同时触发
>         /// </summary>
>         /// <param name="eventType"></param>
>         /// <returns></returns>
>         public static int GetEventID(EventType eventType)
>         {
>             return (int)eventType;
>         }
>         
>         /// <summary>
>         /// 获取事件ID
>         /// 此事件ID属于类级别,可以通过<b>类型+事件类型</b>调用
>         /// 同一类型上同种事件会被同时触发
>         /// </summary>
>         /// <param name="type">挂在事件的类型</param>
>         /// <param name="eventType">事件类型(触发类型)</param>
>         /// <param name="istoeventtype">在类型为null值，是否转成 通过事件类型触发</param>
>         /// <returns></returns>
>         public static int GetEventID(Type type, EventType eventType,bool istoeventtype = false)
>         {
>             if (type == null && istoeventtype)
>                 return GetEventID(eventType);
>             else if (type == null)
>                 return -1;
>             else
>                 return type.GetHashCode() * (int)eventType;
>         }
> 
>         /// <summary>
>         /// 获取事件ID
>         /// 此事件ID数据实例级别,可以通过<b>实例+事件类型调用</b>
>         /// </summary>
>         /// <param name="instance">实例</param>
>         /// <param name="eventType">事件类型(触发类型)</param>
>         /// <param name="istoeventtype">在类型为null值，是否转成 通过事件类型触发</param>
>         /// <returns></returns>
>         public static int GetEventID(UnityEngine.Object instance, EventType eventType, bool istoeventtype = false)
>         {
>             if (instance == null && istoeventtype)
>                 return GetEventID(eventType);
>             else if (instance == null)
>                 return -1;
>             else
>                 return instance.GetInstanceID() * (int)eventType;
>         }
> 
>         /// <summary>
>         /// 添加监听事件
>         /// </summary>
>         /// <param name="eventType">事件类型</param>
>         /// <param name="handler">事件</param>
>         public void AddListener(int eventid, Action<object, IEventArgs> handler)
>         {
>             Action<object, IEventArgs> eventHandler =null;
>             if (!_allActions.TryGetValue(eventid, out eventHandler))
>                 _allActions[eventid] = handler;
>             else
>                 eventHandler += handler;
>         }
> 
>         /// <summary>
>         /// 移除监听事件
>         /// </summary>
>         /// <param name="instance">实例</param>
>         /// <param name="eventType">事件类型</param>
>         /// <param name="handler">事件</param>
>         public void RemoveListener(int eventid, Action<object,IEventArgs> handler)
>         {
>             Action<object, IEventArgs> eventHandler = null;
>             if (!_allActions.TryGetValue(eventid, out eventHandler))
>                 return;
>             else
>             {
>                 eventHandler -= handler;
>                 if (eventHandler == null)
>                     _allActions.Remove(eventid);
>             }
>         }
> 
>         /// <summary>
>         /// 触发事件
>         /// </summary>
>         /// <param name="eventid"></param>
>         public void Trigger(UnityEngine.Object sender, int eventid,IEventArgs eventArgs = null)
>         {
>             HanleEvent(sender, eventid,eventArgs);
>         }
> 
>         #endregion
> 
>         #region 内部函数
>         private void HanleEvent(UnityEngine.Object sender, int eventid, IEventArgs eventArgs = null)
>         {
>             Action<object, IEventArgs> eventHandler = null;
>             if (!_allActions.TryGetValue(eventid, out eventHandler))
>             {
> #if UNITY_EDITOR
>                 UnityEngine.Debug.LogError("找不到事件! \n " + System.Environment.StackTrace);
> #endif
>                 return;
>             }
>             eventHandler(sender, eventArgs);
>         }
>         #endregion
> 
>         #region 重载函数
>         /// <summary>
>         /// 清空所有事件
>         /// </summary>
>         public void OnClose()
>         {
>             _allActions.Clear();
>         }
>         #endregion
>     }
> 
>     //public void RegisterAndCallEvent(){
>     //    EventManager eventManager = new EventManager();
>     //    int eventid = -1;
>     //            if ((eventid = EventManager.GetEventID(this, EventType.HttpDownLoadSuccess)) != -1)
>     //                eventManager.AddListener(eventid,OnHttpDownLoad);
> 
>     //    eventManager.Trigger(null, eventid);
>     //}
> 
>     //private void OnHttpDownLoad(object arg1, IEventArgs arg2)
>     //{
>     //    //....
>     //}
> 
> }
> ```

至于这个可以配合对象池试试，不过在每次都需要绑定事件都需要去获取id，还是比较麻烦的，而且基本监听事件的地方多半都不能直接拿到事件的对象，最好就是配合对象池取，然后`EventType`的扩展也是需要单独处理，具体可以实际使用试试

**Comment by SixGodZhang** [comment]
@coding2233 
多谢指教,
1. 确实如此，开发的爽才是最重要的。
2.像绑定事件获取ID这种，我重新封了个接口，类似于下面这种，调用起来更加方便点
RegisterEvent(System.Object instance, EventType eventType, Action<System.Object, IEventArgs> callback)
3.关于在实际使用的问题，我找机会试试
