### ISSUE TITLE
资源下载失败，本地仍会缓存

### ISSUE THREAD

**Issue by SixGodZhang** [coding2233/UnityGameFramework#6]
大佬，仅做个记录。
location:WebDownloadMonoHelper.cs#L31
···
request.downloadHandler = new DownloadHandlerFile(localPath);
···

问题描述:当资源下载失败时，本地仍会创建对应的文件。会影响资源重新下载
解决思路:自定义一个DownloadHandle

**Comment by coding2233** [comment]
其实因为在成功下载完所有的资源的时候，才会重写本地的version.txt，如果下载失败，重新下载的时候并不会影响重新下载，但是如果想在下载更新失败后，仍然能运行程序就可能需要再单独处理下载的逻辑，其次，如果把断点续传写上的话，应该就可以很好的处理这个问题了

**Comment by SixGodZhang** [comment]
是的
